# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_ID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='T_Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('BugStatus', models.CharField(max_length=50)),
                ('BugTitle', models.CharField(max_length=100)),
                ('BugContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='T_Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DemandName', models.CharField(max_length=100)),
                ('DemandDescribe', models.TextField()),
                ('Level', models.IntegerField()),
                ('DemandStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='T_DemandAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BugId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Bug')),
                ('DemandId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Demand')),
            ],
        ),
        migrations.CreateModel(
            name='T_DemandBugLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogContent', models.TextField()),
                ('BugId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Bug')),
                ('DemandId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Demand')),
            ],
        ),
        migrations.CreateModel(
            name='T_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='T_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogContent', models.CharField(max_length=50)),
                ('CreateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=50)),
                ('MemberName', models.CharField(max_length=100)),
                ('PictureUrl', models.CharField(max_length=200)),
                ('IsUsed', models.BooleanField()),
                ('IsSuAdmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='T_Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MimoContent', models.TextField(blank=True, null=True)),
                ('CreateTime', models.DateTimeField(auto_now=True)),
                ('MemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Member')),
            ],
        ),
        migrations.CreateModel(
            name='T_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleName', models.CharField(max_length=50)),
                ('Level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='T_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=100)),
                ('ProjectStartTime', models.DateTimeField()),
                ('ProjectEndTime', models.DateTimeField()),
                ('ProjectDescribe', models.TextField(blank=True, null=True)),
                ('ProjectStatus', models.CharField(max_length=50)),
                ('AdminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Admin')),
            ],
        ),
        migrations.CreateModel(
            name='T_ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isHead', models.BooleanField()),
                ('AdminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Admin')),
                ('MemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Member')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Project')),
            ],
        ),
        migrations.CreateModel(
            name='T_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=100)),
                ('TestContent', models.TextField()),
                ('TestStatus', models.CharField(max_length=50)),
                ('TestStartTime', models.DateTimeField(auto_now=True)),
                ('TestEndTime', models.DateTimeField(auto_now=True)),
                ('ModuleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Module')),
                ('ProjectMemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember')),
            ],
        ),
        migrations.CreateModel(
            name='T_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicContent', models.TextField()),
                ('CreateTime', models.DateTimeField(auto_now=True)),
                ('Department_ID', models.CharField(max_length=50)),
                ('MemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Member')),
            ],
        ),
        migrations.CreateModel(
            name='T_TopicReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReplyContent', models.TextField()),
                ('Level', models.IntegerField()),
                ('CreateTime', models.DateTimeField(auto_now=True)),
                ('MemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Member')),
            ],
        ),
        migrations.CreateModel(
            name='T_Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoteContent', models.TextField()),
                ('CreateTime', models.DateTimeField(auto_now=True)),
                ('Department_ID', models.CharField(max_length=50)),
                ('MemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Member')),
            ],
        ),
        migrations.CreateModel(
            name='T_VoteOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OptionContent', models.TextField()),
                ('OptionNum', models.IntegerField()),
                ('VoteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Vote')),
            ],
        ),
        migrations.AddField(
            model_name='t_module',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember'),
        ),
        migrations.AddField(
            model_name='t_log',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember'),
        ),
        migrations.AddField(
            model_name='t_document',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember'),
        ),
        migrations.AddField(
            model_name='t_demandbuglog',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember'),
        ),
        migrations.AddField(
            model_name='t_demandassigned',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember'),
        ),
        migrations.AddField(
            model_name='t_demand',
            name='ModuleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Module'),
        ),
        migrations.AddField(
            model_name='t_demand',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember'),
        ),
        migrations.AddField(
            model_name='t_bug',
            name='ModuleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Module'),
        ),
        migrations.AddField(
            model_name='t_bug',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember'),
        ),
        migrations.AddField(
            model_name='t_bug',
            name='TestId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Test'),
        ),
        migrations.AddField(
            model_name='t_admin',
            name='MemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Member'),
        ),
    ]
