# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_ID', models.CharField(max_length=50, verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8id')),
            ],
        ),
        migrations.CreateModel(
            name='T_Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField(verbose_name=b'bug\xe7\xad\x89\xe7\xba\xa7')),
                ('BugStatus', models.CharField(max_length=50, verbose_name=b'bug\xe5\xbd\x93\xe5\x89\x8d\xe7\x8a\xb6\xe6\x80\x81')),
                ('BugTitle', models.CharField(max_length=100, verbose_name=b'bug\xe6\xa0\x87\xe9\xa2\x98')),
                ('BugContent', models.TextField(verbose_name=b'bug\xe5\x85\xb7\xe4\xbd\x93\xe5\x86\x85\xe5\xae\xb9')),
            ],
        ),
        migrations.CreateModel(
            name='T_Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DemandName', models.CharField(max_length=100, verbose_name=b'\xe9\x9c\x80\xe6\xb1\x82\xe5\x90\x8d\xe7\xa7\xb0')),
                ('DemandDescribe', models.TextField(verbose_name=b'\xe9\x9c\x80\xe6\xb1\x82\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('Level', models.IntegerField(verbose_name=b'\xe4\xbc\x98\xe5\x85\x88\xe7\xba\xa7')),
                ('DemandStatus', models.CharField(max_length=50, verbose_name=b'\xe9\x9c\x80\xe6\xb1\x82\xe7\x8a\xb6\xe6\x80\x81')),
            ],
        ),
        migrations.CreateModel(
            name='T_DemandAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BugId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Bug', verbose_name=b'Bugid(bugid\xe5\x92\x8c\xe9\x9c\x80\xe6\xb1\x82id\xe4\xba\x8c\xe8\x80\x85\xe6\x9c\x89\xe4\xb8\x80\xe4\xb8\xaa\xe5\x8d\xb3\xe5\x8f\xaf)')),
                ('DemandId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Demand', verbose_name=b'\xe9\x9c\x80\xe6\xb1\x82id')),
            ],
        ),
        migrations.CreateModel(
            name='T_DemandBugLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogContent', models.TextField(verbose_name=b'\xe6\x97\xa5\xe5\xbf\x97\xe5\x86\x85\xe5\xae\xb9')),
                ('BugId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Bug', verbose_name=b'bug\xe7\x9a\x84id')),
                ('DemandId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Demand', verbose_name=b'\xe9\x9c\x80\xe6\xb1\x82id')),
            ],
        ),
        migrations.CreateModel(
            name='T_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentName', models.CharField(max_length=50, verbose_name=b'\xe6\x96\x87\xe6\xa1\xa3\xe5\x90\x8d\xe7\xa7\xb0')),
                ('DocumentUrl', models.CharField(max_length=100, verbose_name=b'\xe6\x96\x87\xe6\xa1\xa3\xe8\xb7\xaf\xe5\xbe\x84')),
            ],
        ),
        migrations.CreateModel(
            name='T_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogContent', models.CharField(max_length=50, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe5\x86\x85\xe5\xae\xb9\xef\xbc\x8c\xe6\xa0\xb9\xe6\x8d\xaexml\xe8\xae\xb0\xe5\xbd\x95')),
                ('CreateTime', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe6\x97\xb6\xe9\x97\xb4')),
            ],
        ),
        migrations.CreateModel(
            name='T_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=50, verbose_name=b'\xe6\x88\x90\xe5\x91\x98\xe8\xb4\xa6\xe5\x8f\xb7\xef\xbc\x88\xe4\xbc\x81\xe4\xb8\x9a\xe5\x8f\xb7\xe5\x86\x85\xe5\xbf\x85\xe9\xa1\xbb\xe5\x94\xaf\xe4\xb8\x80\xef\xbc\x89')),
                ('MemberName', models.CharField(max_length=100, verbose_name=b'\xe6\x88\x90\xe5\x91\x98\xe5\xa7\x93\xe5\x90\x8d')),
                ('PictureUrl', models.CharField(max_length=200, verbose_name=b'\xe5\xa4\xb4\xe5\x83\x8f\xe5\x9b\xbe\xe7\x89\x87\xe8\xb7\xaf\xe5\xbe\x84')),
                ('IsUsed', models.BooleanField(verbose_name=b'\xe8\xaf\xa5\xe8\xb4\xa6\xe5\x8f\xb7\xe6\x98\xaf\xe5\x90\xa6\xe8\xa2\xab\xe5\x88\xa0\xe9\x99\xa4')),
                ('IsSuAdmin', models.BooleanField(verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe4\xb8\xba\xe8\xb6\x85\xe7\xba\xa7\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98')),
            ],
        ),
        migrations.CreateModel(
            name='T_Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MimoContent', models.TextField(blank=True, null=True, verbose_name=b'\xe5\xa4\x87\xe5\xbf\x98\xe5\xbd\x95\xe5\x86\x85\xe5\xae\xb9')),
                ('CreateTime', models.DateTimeField(auto_now=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('MemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Member', verbose_name=b'\xe6\x88\x90\xe5\x91\x98id')),
            ],
        ),
        migrations.CreateModel(
            name='T_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleName', models.CharField(max_length=50, verbose_name=b'\xe6\xa8\xa1\xe5\x9d\x97\xe5\x90\x8d\xe7\xa7\xb0')),
                ('Level', models.IntegerField(verbose_name=b'\xe6\xa8\xa1\xe5\x9d\x97\xe4\xbc\x98\xe5\x85\x88\xe7\xba\xa7')),
            ],
        ),
        migrations.CreateModel(
            name='T_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=100, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0')),
                ('ProjectStartTime', models.DateTimeField(verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('ProjectEndTime', models.DateTimeField(verbose_name=b'\xe9\xa2\x84\xe8\xae\xa1\xe9\xa1\xb9\xe7\x9b\xae\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('ProjectDescribe', models.TextField(blank=True, null=True, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('ProjectStatus', models.CharField(max_length=50, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe5\xbd\x93\xe5\x89\x8d\xe7\x8a\xb6\xe6\x80\x81')),
                ('AdminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Admin', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\xaf\xa5\xe9\xa1\xb9\xe7\x9b\xae\xe7\x9a\x84\xe5\xad\x90\xe9\x83\xa8\xe9\x97\xa8\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98')),
            ],
        ),
        migrations.CreateModel(
            name='T_ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isHead', models.BooleanField(verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe4\xb8\xba\xe9\xa1\xb9\xe7\x9b\xae\xe8\xb4\x9f\xe8\xb4\xa3\xe4\xba\xba')),
                ('AdminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Admin', verbose_name=b'\xe5\x8a\xa0\xe5\x85\xa5\xe8\xaf\xa5\xe7\xa8\x8b\xe5\xba\x8f\xe5\x91\x98\xe7\x9a\x84\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98id')),
                ('MemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Member', verbose_name=b'\xe6\x88\x90\xe5\x91\x98id')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Project', verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xaeid')),
            ],
        ),
        migrations.CreateModel(
            name='T_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=100, verbose_name=b'\xe6\xb5\x8b\xe8\xaf\x95\xe5\x90\x8d\xe7\xa7\xb0')),
                ('TestContent', models.TextField(verbose_name=b'\xe6\xb5\x8b\xe8\xaf\x95\xe5\x86\x85\xe5\xae\xb9')),
                ('TestStatus', models.CharField(max_length=50, verbose_name=b'\xe6\xb5\x8b\xe8\xaf\x95\xe7\x8a\xb6\xe6\x80\x81')),
                ('TestStartTime', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\xb5\x8b\xe8\xaf\x95\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('TestEndTime', models.DateTimeField(auto_now=True, verbose_name=b'\xe9\xa2\x84\xe8\xae\xa1\xe6\xb5\x8b\xe8\xaf\x95\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('ModuleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Module', verbose_name=b'\xe6\xb5\x8b\xe8\xaf\x95\xe6\x89\x80\xe5\xb1\x9e\xe6\xa8\xa1\xe5\x9d\x97')),
                ('ProjectMemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\xb5\x8b\xe8\xaf\x95\xe7\x9a\x84\xe9\xa1\xb9\xe7\x9b\xae\xe7\xbb\x84\xe6\x88\x90\xe5\x91\x98id')),
            ],
        ),
        migrations.CreateModel(
            name='T_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicContent', models.TextField(verbose_name=b'\xe8\xaf\x9d\xe9\xa2\x98\xe5\x86\x85\xe5\xae\xb9')),
                ('CreateTime', models.DateTimeField(auto_now=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('Department_ID', models.CharField(max_length=50, verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8id')),
                ('MemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Member', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xbaid')),
            ],
        ),
        migrations.CreateModel(
            name='T_TopicReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReplyContent', models.TextField(verbose_name=b'\xe5\x9b\x9e\xe5\xa4\x8d\xe5\x86\x85\xe5\xae\xb9')),
                ('Level', models.IntegerField(verbose_name=b'\xe5\x9b\x9e\xe5\xa4\x8d\xe6\xa5\xbc\xe5\xb1\x82')),
                ('CreateTime', models.DateTimeField(auto_now=True, verbose_name=b'\xe5\x9b\x9e\xe5\xa4\x8d\xe6\x97\xb6\xe9\x97\xb4')),
                ('MemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Member', verbose_name=b'\xe6\x88\x90\xe5\x91\x98id')),
            ],
        ),
        migrations.CreateModel(
            name='T_Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoteContent', models.TextField(verbose_name=b'\xe8\xaf\x9d\xe9\xa2\x98\xe5\x86\x85\xe5\xae\xb9')),
                ('CreateTime', models.DateTimeField(auto_now=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('Department_ID', models.CharField(max_length=50, verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8id')),
                ('MemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Member', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xbaid')),
            ],
        ),
        migrations.CreateModel(
            name='T_VoteOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OptionContent', models.TextField(verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9\xe5\x86\x85\xe5\xae\xb9')),
                ('OptionNum', models.IntegerField(verbose_name=b'\xe6\x8a\x95\xe7\xa5\xa8\xe4\xba\xba\xe6\x95\xb0')),
                ('VoteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Vote', verbose_name=b'\xe6\x8a\x95\xe7\xa5\xa8id')),
            ],
        ),
        migrations.AddField(
            model_name='t_module',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xbaid'),
        ),
        migrations.AddField(
            model_name='t_log',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember', verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe6\x88\x90\xe5\x91\x98id'),
        ),
        migrations.AddField(
            model_name='t_document',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\x87\xe6\xa1\xa3\xe9\xa1\xb9\xe7\x9b\xae\xe7\xbb\x84\xe6\x88\x90\xe5\x91\x98id'),
        ),
        migrations.AddField(
            model_name='t_demandbuglog',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember', verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xa5\xe5\xbf\x97\xe7\x9a\x84\xe9\xa1\xb9\xe7\x9b\xae\xe7\xbb\x84\xe6\x88\x90\xe5\x91\x98id'),
        ),
        migrations.AddField(
            model_name='t_demandassigned',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember', verbose_name=b'\xe6\x8c\x87\xe6\xb4\xbe\xe9\xa1\xb9\xe7\x9b\xae\xe7\xbb\x84\xe6\x88\x90\xe5\x91\x98id'),
        ),
        migrations.AddField(
            model_name='t_demand',
            name='ModuleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Module', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe6\xa8\xa1\xe5\x9d\x97id'),
        ),
        migrations.AddField(
            model_name='t_demand',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x88\x90\xe5\x91\x98id'),
        ),
        migrations.AddField(
            model_name='t_bug',
            name='ModuleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Module', verbose_name=b'bug\xe6\x89\x80\xe5\xb1\x9e\xe6\xa8\xa1\xe5\x9d\x97'),
        ),
        migrations.AddField(
            model_name='t_bug',
            name='ProjectMemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_ProjectMember', verbose_name=b'\xe6\x8f\x90\xe5\x87\xbabug\xe9\xa1\xb9\xe7\x9b\xae\xe7\xbb\x84\xe6\x88\x90\xe5\x91\x98id'),
        ),
        migrations.AddField(
            model_name='t_bug',
            name='TestId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Test', verbose_name=b'bug\xe6\x89\x80\xe5\xb1\x9e\xe6\xb5\x8b\xe8\xaf\x95\xef\xbc\x88\xe5\x8f\xaf\xe4\xb8\xba\xe7\xa9\xba\xef\xbc\x89'),
        ),
        migrations.AddField(
            model_name='t_admin',
            name='MemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdb.T_Member', verbose_name=b'\xe6\x88\x90\xe5\x91\x98id'),
        ),
    ]
